### ISSUE TITLE
navigation-hotkeys: please remove Esc toggle

### ISSUE THREAD

**Issue by stas00** [ipython-contrib/jupyter_contrib_nbextensions#1334]
It took me a while to hunt this one down. This really useful navigation-hotkeys extension adds a problematic hotkey: `esc - toggle to edit mode`, which is already assigned to `switch to command mode`. This breaks a normal use flow where one would hit Esc to switch from any mode to Command mode followed by a custom command mode keyboard shortcut.

Once this extension is enabled `Esc` behavior becomes non-deterministic and if the current cell is not visible one can't tell the current mode - should I hit Esc or not? So for example I end up typing `ii` when I'm trying to interrupt the kernel, since hitting `Esc-ii` happened to be from an already 'command mode', and moving me into edit mode and entering 'ii' to the cell.

Please consider removing this shortcut or making it configurable on the user side. At the moment I have to disable this extension and manually re-insert all but one shortcut from it.

Thank you.

**Comment by JSpenced** [comment]
You might want to checkout my pull request fyi. I've fixed this issue as I removed it in my pull since it can be set in the notebook.json file with the default command. Also, I updated it so the command palette works right. Let me if it doesn't work on your pc.

**Comment by stas00** [comment]
Thank you, @JSpenced.

I don't see any difference in its behavior. Esc still toggles back and force between edit/cmd modes.

I installed your branch:
```
pip3 install git+https://github.com/JSpenced/jupyter_contrib_nbextensions.git@update-for-jupyter-and-remove-redundant-keyspip3 install git+https://github.com/JSpenced/jupyter_contrib_nbextensions.git@update-for-jupyter-and-remove-redundant-keys
```
then enabled Navigation-Hotkeys, restarted jupyter. The hotkeys provided by this module work. And Esc is still a problem.

**Comment by JSpenced** [comment]
For installation, you could just copy over the modified main.js file into your `nbextensions/navigation-keys` folder. Or copy the navigation keys to `nav-keys-modified` and replace the `main.js`. Activate that plug-in. I can't see why those would be combined into one binding as I completely removed the command from the file. Jupyter just overwrites bindings so at least one should be set I think.

Yeah, I was confused about those keybindings as they were written in a non-standard way in the javascript file. I wasn't really sure what they were originally because I wasn't using the plug-in before. I got rid of split-cell-at-cursor as that is redundant with the jupyter binding just as enter edit mode was binded to escape.

Add the `edit` part below into your `notebook.json` file to get that binding combination back and the escape one is included (optional) to get the original behavior for `Esc` back. I didn't manually add these into the plug-in because I thought it was unnecessary. Maybe I should just make my own plug-in because mainly I wanted emacs style bindings for navigating cells. This one should probably be directly backward compatible.


 ```
"keys": {
    "edit": {
      "bind": {
"Alt-Shift-=": "jupyter-notebook:split-cell-at-cursor",
 "Alt-minus": "navigation_hotkeys:merge-cell-with-previous-cell",
    }
    },
 "keys": {
    "command": {
      "bind": {
`"Esc": "jupyter-notebook:enter-edit-mode",`
}
    }
}

```

**Comment by JSpenced** [comment]
I can create a commit that fixes these problems and adds the bindings in, but I really don't see the point of including a command already in Jupyter core.

**Comment by JSpenced** [comment]
FYI, you should be able to do this with the old navigation-hotkeys but this is untested:
```
"keys": {
   "command": {
     "unbind": {
`"Esc"
}
   }
```

**Comment by stas00** [comment]
Well, I'm just showing the results of installing your version, @JSpenced. I already chose not to use this extension, so I have my own bindings.

Your current implementation not only removes one binding, but it wrongly assigns a different function to an existing binding, as I shared in the pasted from config screen Alt-add started doing what Alt-remove was doing before.

This is unrelated to the issue, which was specifically about leaving Esc functionality matching the core, but surely this proposed removal of several bindings leads to not-backward compatible changes, since now anybody who's used to have the bindings of navigation-hotkeys will suddenly have them gone on update. I'm not saying this is wrong, but this is just not a great practice where a plugin update leads to different bindings. Normally it should go through at least a cycle of deprecation, where perhaps if someone uses the old key you tell them the new key and/or how to rebind back to the old one, or a legacy bindings option in the config. Perhaps there are other options.

**Comment by stas00** [comment]
>Maybe I should just make my own plug-in because I primarily wanted emacs style bindings for navigating cells.

May be instead of hardcoded bindings the extension could let users override any and provide pre-made sets of those? (emacs, vi, etc.?)

**Comment by stas00** [comment]
Neither. I'm not sure why the doc displayed in the extension manager for this extension shows +/- - the way it's currently coded - they are actually add/subtract keys in the numpad. Which was probably not the best choice in first place, since I don't think those keys even exist on some limited keyboards like on chromebooks.

```
        'alt-add' : {
            help    : 'split cell',
            help_index : 'eb',
            handler : function() {
                IPython.notebook.split_cell();
                IPython.notebook.edit_mode();
                return false;
            }
        },
        'alt-subtract' : {
            help    : 'merge cell',
            help_index : 'eb',
            handler : function() {
                var i = IPython.notebook.get_selected_index();
                if (i > 0) {
                    var l = IPython.notebook.get_cell(i-1).code_mirror.lineCount();
                    IPython.notebook.merge_cell_above();
                    IPython.notebook.get_selected_cell().code_mirror.setCursor(l,0);
                    }
            }
        },
```

**Comment by JSpenced** [comment]
Ahhh, now I get it. Yeah, I don't have those keys on my macbook so was confused. Okay, coding it up and I'll put in a params for escape. Push soon.

**Comment by JSpenced** [comment]
Should be completely backwards compatible and has the function requested here.

Let me know if you get any issues.

Cheers

**Comment by stas00** [comment]
For some reason updating is a problem, Tried reinstalling with pip several times, eventually it worked after I did:
```
jupyter contrib nbextension uninstall --user
jupyter contrib nbextension install --user
```
and only then it updated .local/share/jupyter/nbextensions/ - but it was a bad choice since I lost the previous config of the enabled extensions :(

The latest incarnation of your version of navigation-hotkeys is missing the alt-add / split entry. Alt-subtract and the rest works.

**Comment by JSpenced** [comment]
Sorry, I can't test that key and forgot to change it back after testing. Just pushed up to change it to alt-add so all should be good now.

Yeah, I have the repo in a different folder and just paste over nav-keys or just the main.js and hotkeys.yaml.

**Comment by stas00** [comment]
It's all good now, @JSpenced. Thank you.

**Comment by juhasch** [comment]
Merged in PR #1378.
