### ISSUE TITLE
install to custom location

### ISSUE THREAD

**Issue by flying-sheep** [ipython-contrib/jupyter_contrib_nbextensions#607]
i want a way to install the extensions to a custom location (i.e. a location where jupyter can find them globally)

when running `setup.py install`, the files install themselves to a fixed location in my $HOME, unmanaged by pip.

i want to be able to track them with pip or my system’s package manager.

1. please create a way to do this or respect `--prefix` or so
2. how can the extensions be installed systemwide so that jupyter can still find them?

**Comment by jcb91** [comment]
You could try my trav branch, which supports many of the same options as `jupyter nbextension install`:

```
--user
    Perform the operation for the current user
--system
    Perform the operation system-wide
--sys-prefix
    Use sys.prefix as the prefix for configuration files
--config-dir=<Unicode> (ThemystoConfigModifyApp.config_dir)
    Default: ''
    Full path to config directory
```

I'm hoping to merge that branch in as  a PR here eventually...

**Comment by jcb91** [comment]
note that my themysto version requires an additional install step, so it'd require something like:

```
setup.py install
themysto install --sys-prefix
```

The setup.py installs a regular python package, then the `themysto install` command edits a config file to ensure the location of the python package's nbextensions is added to the jupyter notebook nbextensions search path.

**Comment by jcb91** [comment]
(see also #577)

**Comment by flying-sheep** [comment]
cool! so your way basically doesn’t install them to and of the `jupyter_path()`s, but to the pip path and `themysto` activates it?

or, if something still ends up in a `jupyter_path()`, which step does that?

**Comment by jcb91** [comment]
yep, first one:

none of the funcitonal files are copied into any of the `jupyter_path()`s, they all stays in the pip path.
The `themysto` call only creates/modifies a config file (which will be in one of jupyter_config_path() folders, depending on which arguments are passed) to activate everything.

**Comment by jcb91** [comment]
also, if you run `themysto` with the `--debug` flag, it should tell you which files it's editing as it runs.

**Comment by flying-sheep** [comment]
[done](https://aur.archlinux.org/packages/jupyter-nbextensions-git/)

**Comment by jcb91** [comment]
ace 😄

**Comment by jcb91** [comment]
@flying-sheep FYI, I've merged trav into my master branch now.

**Comment by flying-sheep** [comment]
updated the package. hmm, either i stay on git or i have to rename it to “themysto”, since your fork’s tags don’t match upstream’s versions, right?

**Comment by jcb91** [comment]
> hmm, either i stay on git or i have to rename it to “themysto”, since your fork’s tags don’t match upstream’s versions, right?

I'm not sure what you mean? My fork's `master` tag no longer matches the main repo's `master`, correct. There's PR #626 to merge them, but it's proving difficult for people to review because there are so many changes (mostly just straight renames, but still show up as changes on github so lots of stuff doesn't get rendered).

**Comment by flying-sheep** [comment]
i meant that you have a 0.4 tag and the main repo doesn’t, so your 0.4 doesn’t match nbextensions 0.4

**Comment by jcb91** [comment]
Oh, I see! Yes, the tags (0.0.1 through 0.0.4) all refer to my `themysto`
version. The main nbextensions repo hasn't adopted a proper version yet,
we've actually just had `alpha` all along (which incidentally isn't pep440
compliant anyway).

**Comment by jcb91** [comment]
This should hopefully now be fixed in master, with version 0.1.0 using our shiny new 2-part install method:

    pip install jupyter_contrib_nbextensions
    jupyter contrib nbextension install --sys-prefix

or equivalently with the `--system` flag instead of `--sys-prefix`, to perform a system-wide install.

I'll close assuming this is fixed, but please reopen/open a new issue if the new method doesn't work as intended.

**Comment by flying-sheep** [comment]
well, it doesn’t:

```
community-contributed spice for Jupyter Interactive Computing

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--debug
    set log level to logging.DEBUG (maximize logging output)
-y
    Answer yes to any questions instead of prompting.
--generate-config
    generate default config file
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.

To see all available configurables, use `--help-all`

[JupyterContribApp] CRITICAL | Bad config encountered during initialization:
[JupyterContribApp] CRITICAL | Unrecognized flag: '--sys-prefix'
```

**Comment by flying-sheep** [comment]
and i get this:

 ```console
$ jupyter contrib nbextension install
[...]
Please supply at least one subcommand:
$ jupyter contrib nbextension
[...]
Please supply at least one subcommand:
$ jupyter contrib
[...]
Please supply at least one subcommand:
```

ummm

**Comment by juhasch** [comment]
What happens if you call `jupyer-contrib` or `jupyter-contrib-nbextension` ?
They should be in your path and will be called by the above commands.

**Comment by flying-sheep** [comment]
```console
$ jupyter contrib
community-contributed spice for Jupyter Interactive Computing

Subcommands
-----------

Subcommands are launched as `jupyter contrib cmd [args]`. For information on
using subcommand 'cmd', do: `jupyter contrib cmd -h`.

nbextension
    Install or uninstall all of jupyter_contrib_nbextensions.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

-y
    Answer yes to any questions instead of prompting.
--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.

To see all available configurables, use `--help-all`

Please supply at least one subcommand: nbextension
$ jupyter contrib nbextension
Please supply at least one subcommand: install, migrate, uninstall

```

**Comment by flying-sheep** [comment]
also this:

```console
$ jupyter contrib nbextension install --prefix=...
[…]
notebook.nbextensions.ArgumentConflict: cannot specify more than one of user, sys_prefix, prefix, or nbextensions_dir
```

**Comment by juhasch** [comment]
Yes, `--sys-prefix` is a flag. Does ist do what you expect ?

Actually, there are two different packages that use `juyter contrib ...`:
* jupyter_contrib_core -> `jupyter contrib`
* jupyter_contrib_nbextension -> `jupyter contrib nbextension`

**Comment by flying-sheep** [comment]
apparently `--prefix` does what i want, but it doesn’t work. please see my above comment.

**Comment by juhasch** [comment]
Sorry if I am a little dense here:
```
 jupyter-contrib-nbextension install --sys-prefix
```
Works for me. 
```
 jupyter-contrib-nbextension install --sys-prefix=..
```
Doesn't. Which is how the Jupyter nbextensions stuff works, too:
```
 jupyter nbextension install --help
```

**Comment by flying-sheep** [comment]
i understood that, and found out i need to use `--prefix`. not sys-prefix, not system.

but `--prefix` has a bug: if it is set, both `user=True` and `prefix='...'` will be passed to `notebook.nbextensions.install_nbextension`, and i get `ArgumentConflict: cannot specify more than one of user, sys_prefix, prefix, or nbextensions_dir`

**Comment by jcb91** [comment]
late to the table here, but yes, as @flipphillips says, this is a bug relating to `user` defaulting to `True`. In fact, this stems from a bug in the upstream notebook implementation of `notebook.serverextensions.ToggleServerExtensionApp`, which is the app I started from when making ours...

**Comment by flying-sheep** [comment]
you mean @flying-sheep :smile:

**Comment by jcb91** [comment]
d'oh, so I do @flying-sheep! Stupid autocomplete, apologies @flipphillips, nothing to see here...

**Comment by flying-sheep** [comment]
i’m trying to fix this in #709, but have no idea what goes wrong there…

**Comment by jcb91** [comment]
thanks for the PRs! I'm out this evening, but will take a look once I get
back to a computer. It may be simplest to just have user default to false...

**Comment by jcb91** [comment]
> the tests are a bit too convoluted to be helpful

If you can think of better ways, I'm all ears :)

**Comment by flying-sheep** [comment]
no idea, i just don’t see how my changes cause the installation dir to be empty… i need more low-level changes that catch whatever i broke :cry:

**Comment by jcb91** [comment]
as far as I can tell from https://travis-ci.org/ipython-contrib/jupyter_contrib_nbextensions/jobs/148539775#L416-L428, it seems that somehow you've ended up making the default install go into `sys.prefix`, instead of the user directories at `env_vars`. I can't say I understand how that happened though...

**Comment by flying-sheep** [comment]
ah, i see! i take back what i said about the tests, they *are* well interpretable.

but still: how?! i didn’t touch the sys-prefix flag, and never set its value to something truthy…

**Comment by jcb91** [comment]
Yeah, the how mystifies me too, I can't see anything in the diff that should affect this at all...
